version: "2"
plugins:
    csslint:
        enabled: true
    duplication:
        enabled: true
        config:
            languages:
                - javascript
                - typescript
    eslint:
        enabled: true
        channel: "channel/eslint-8"
    fixme:
        enabled: true
    nodesecurity:
        enabled: true
exclude_patterns:
    - dist/
    - "**/node_modules/"
    - "**/__tests__/"
