# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Release

on:
    push:
        branches:
            - master

permissions:
    contents: write
    pages: write
    actions: read

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    lint:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  # We need to fetch all branches and commits so that Nx affected has a base to compare against.
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Derive appropriate SHAs for base and head for `nx affected` commands
              id: setSHAs
              uses: nrwl/nx-set-shas@v4

            - name: Run linting and formatting checks
              run: npx nx affected -t format:check lint --base origin/master

    publish-npm:
        needs: lint
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
              run: npm audit signatures

            - name: Print Environment Info
              run: npx nx report

            - name: Create release
              run: |
                  git config --global user.email "webb.c.brandon@gmail.com"
                  git config --global user.name "Github Actions"
                  npx nx release --skip-publish

            - name: Publish packages
              run: npx nx release publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
